### ISSUE TITLE
Todo [FIXES + MISC]

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/Bewitchment#2]
The following need to be fixed:

- [x] Some brews that change blocks do not respect rotations of things like stairs
- [ ] Stairs, slabs, and fences need a rewrite. They are kind of fucky.
- [ ] Beehive gen, if those are kept. They use the ore spawning system, but in trees, currently.
- [x] Possible performance issue with the oven. More clarification on the performance issue is probably needed.
- [ ] Fix between this mod and rustic, to allow brews from this mod to be created once more due to rustic toying with glass bottles.
- [ ] Brews have a hard time landing on a target if the target is a mob, or presumably, a player

The following need implementation:

- [x] Port over Covens rituals
- [ ] Port over other things
- [ ] Set up cypress generation
- [ ] JEI plugin for brewing  
- [ ] Other things
- [ ] Love potion. Use silphium as the ingredient, use a different ingredient for flower growth.

The following are being worked on:

- [x] Stews in the kettle
- [ ] Fences and walls for some of the blocks added
- [ ] Positive fortunes. Just need ideas.
- [ ] Tarot cards
- [x] Brooms
- [x] Recreations of the old crops from Covens
- [ ] Witchweed + infested soil mechanics (WIP)

Fixmes and Todos from the code, plus miscellaneous things:

- [ ] Fix Girdle of the Wooded rendering, it is apparently acting up.
- [ ] New way of determining color that does not involve wool, so I don't have to throw a crash at players who remove those oredicts that code for color.
- [x] Allow blocks to be placed in cauldron-based stews, as well as metadata for both blocks and items.
- [x] TileOven causes a chunk redraw at every tick. This needs a fix
- [ ] Move brews over to potions at some point
- [ ] Change the way gems are stored on an altar. Implement a gem bowl. Allow it to take oredict definitions, metadata, and more, for maximum mod support.
- [ ] Rewrite the fisheye incantation
- [ ] Grimoire functionality, when the time comes. The class is empty. Same deal with the book of shadows.
- [ ] [Not now son, I'm making... TOAST!](https://www.youtube.com/watch?v=0Ntiphuey8g)
- [ ] Taglocks need to change color when a taglock is taken
- [ ] Animania compat for mycological corruption and grass grow brews, as it replaces vanilla livestock with it's own.
- [ ] Expand the dungeon loot tables, so I can place silphium seeds in dungeons.
- [ ] Add gemstones from this mod to the loot tables for fortunes.
- [x] Allow holy water brews to damage vampiric players
- [ ] Rewrite ME/Fix Energy
- [ ] Come up with a new name for ME
- [ ] Come up with a new recipe for kelp spores.
- [ ] Javadocs
- [ ] New textures for the gemstone blocks
- [ ] Make fumes more chance based.
- [ ] New textures for cold iron
- [ ] Crafting mechanism for cold iron that does not involve a furnace, or any form of heat.
- [ ] Brew that turns infested soil back into farmland, to combat the actions of malicious players with some seeds.

**Comment by Placid-Storm** [comment]
I'm going to suggest a guide book. I loved the Witchery mod and am watching this mod closely. Witchery is actually the primary reason I am still playing 1.7.10. But other than a guide book, are the clay jar working? I was just trying to make them using oak slabs and clay blocks. I tried clay balls first. Clay blocks seem kinda expensive for an item that I will be going through like candy.

**Comment by Sunconure11** [comment]
@Placid-Storm A guide book is planned.

**Comment by zabi94** [comment]
Ticked a bunch of these

**Comment by zabi94** [comment]
https://trello.com/b/CdhWq4v9/bewitchment  
Team members, I need to add you to the group for editing permissions, send me your trello email via pm
